//! Assembling the four scenarios into one `.daw` document.

use std::path::{Path, PathBuf};

use daw_proto::item::{Item, Take};
use daw_proto::track::Track;
use dawfile_standalone::document::{DawDocument, ItemNode, SourceRef, TakeNode, TrackNode};
use dawfile_standalone::id::EntityId;

use crate::Material;

/// Which scenario a track is here to serve.
///
/// The demo project is not a mix — every track earns its place by being
/// the material one of #149's four scenarios needs, and this records
/// which, so a scenario test can find its own tracks without matching
/// on names that vary between sessions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrackRole {
    /// Scenario 1: a real vocal take, for envelope compositing.
    Vocal,
    /// Scenario 2: one close mic of the drum multitrack.
    Drum,
    /// Scenario 3: the synthesized MPE fixture.
    Mpe,
    /// Scenario 4: the Guitar Pro transcription.
    Guitar,
    /// Context — bass, keys, the click. Not under test, but present,
    /// because a scenario that only works in an otherwise-empty project
    /// has not been tested against anything.
    Context,
}

/// A track in the assembled project, with the role that put it there.
#[derive(Debug, Clone)]
pub struct DemoTrack {
    pub role: TrackRole,
    pub name: String,
    pub id: EntityId,
    /// The media behind it, when it is a file on disk.
    pub source: Option<PathBuf>,
}

/// The assembled project.
pub struct Demo {
    pub document: DawDocument,
    pub tracks: Vec<DemoTrack>,
    /// The song the vocal and context tracks came from.
    pub song: String,
}

impl Demo {
    /// Every track serving one scenario.
    pub fn by_role(&self, role: TrackRole) -> Vec<&DemoTrack> {
        self.tracks.iter().filter(|t| t.role == role).collect()
    }

    /// Whether a scenario has material at all. A scenario test asserts
    /// on this rather than unwrapping, so a partial machine reports
    /// which part it is missing.
    pub fn covers(&self, role: TrackRole) -> bool {
        self.tracks.iter().any(|t| t.role == role)
    }
}

/// Build the demo project from whatever this machine has.
///
/// Deliberately total: a machine missing the drum multitrack still gets
/// a project with the other three scenarios in it, and
/// [`Demo::covers`] reports the hole. Scenario tests skip on their own
/// role rather than on the project as a whole, so one missing download
/// does not blind all four.
pub fn build(m: &Material) -> Demo {
    let mut document = DawDocument::new("FTS Expression Editor Demo");
    let mut tracks: Vec<DemoTrack> = Vec::new();

    // The inventory recommends the PNG sessions over the delivered
    // multitracks: real takes, real vocals, two of them with prior
    // Melodyne passes, and matching MIDI and charts for the same songs.
    let songs = m.songs();
    let song = songs
        .iter()
        // Hannah's Song is the one with named per-instrument drum
        // tracks in its MIDI export, so it is the most useful single
        // session to build on.
        .find(|s| s.name.contains("HANNAH"))
        .or_else(|| songs.first());

    let song_name = song.map(|s| s.name.clone()).unwrap_or_default();

    if let Some(song) = song {
        let stems = m.stems(song);
        // A vocal take, and a few neighbours for context. The session
        // holds up to 99 files; the demo wants the scenario material
        // plus enough around it to be a real document, not all of it.
        for path in pick_vocals(&stems, 2) {
            push_file_track(&mut document, &mut tracks, TrackRole::Vocal, &path);
        }
        for path in pick_context(&stems, 4) {
            push_file_track(&mut document, &mut tracks, TrackRole::Context, &path);
        }
    }

    // Scenario 2 needs bleed, which only real close mics have.
    if let Some(dir) = m.drum_multitrack() {
        for path in close_mics(&dir, 6) {
            push_file_track(&mut document, &mut tracks, TrackRole::Drum, &path);
        }
    }

    // Scenario 4. The roll is built by the importer at test time; the
    // project records where the file is.
    if let Some(gp) = m.guitar_pro() {
        push_file_track(&mut document, &mut tracks, TrackRole::Guitar, &gp);
    }

    // Scenario 3 is the one hole in the material (#159): nothing on the
    // machine is a usable MPE file, so #177 synthesizes it. The track
    // is here with no source — the fixture is generated by the test.
    let id = push_track(&mut document, "MPE Fixture");
    tracks.push(DemoTrack {
        role: TrackRole::Mpe,
        name: "MPE Fixture".into(),
        id,
        source: None,
    });

    document.reindex();
    Demo {
        document,
        tracks,
        song: song_name,
    }
}

/// Vocal takes, by the names the PNG sessions actually use.
fn pick_vocals(stems: &[PathBuf], limit: usize) -> Vec<PathBuf> {
    matching(stems, &["vox", "vocal", "lead", "demovox"], limit)
}

/// Bass, keys and guitar — pitched material that is not the vocal.
fn pick_context(stems: &[PathBuf], limit: usize) -> Vec<PathBuf> {
    matching(stems, &["bass", "keys", "piano", "gtr", "guitar"], limit)
}

fn matching(stems: &[PathBuf], needles: &[&str], limit: usize) -> Vec<PathBuf> {
    stems
        .iter()
        .filter(|p| {
            let name = p
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or_default()
                .to_ascii_lowercase();
            needles.iter().any(|n| name.contains(n))
        })
        .take(limit)
        .cloned()
        .collect()
}

/// The close mics, preferred over overheads and room — bleed between
/// *close* mics is what makes scenario 2 hard.
fn close_mics(dir: &Path, limit: usize) -> Vec<PathBuf> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut wavs: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x.eq_ignore_ascii_case("wav")))
        .collect();
    wavs.sort();
    let close = matching(&wavs, &["kick", "snare", "hat", "tom"], limit);
    if close.is_empty() {
        wavs.into_iter().take(limit).collect()
    } else {
        close
    }
}

fn push_file_track(
    doc: &mut DawDocument,
    tracks: &mut Vec<DemoTrack>,
    role: TrackRole,
    path: &Path,
) {
    let name = path
        .file_stem()
        .and_then(|n| n.to_str())
        .unwrap_or("Track")
        .to_string();
    let id = push_track(doc, &name);

    // Absolute, and deliberately so: the material is 20 GB that must
    // never be copied into the project directory. `self_contained`
    // will report this project as not self-contained, which is the
    // truth about it.
    if let Some(node) = doc.tracks.iter_mut().find(|t| t.id == id) {
        node.items.push(item_for(path));
    }

    tracks.push(DemoTrack {
        role,
        name,
        id,
        source: Some(path.to_path_buf()),
    });
}

fn push_track(doc: &mut DawDocument, name: &str) -> EntityId {
    let id = EntityId::new();
    doc.tracks.push(TrackNode {
        id: id.clone(),
        track: Track {
            guid: id.as_str().to_string(),
            name: name.to_string(),
            ..Default::default()
        },
        parent: None,
        envelopes: Vec::new(),
        items: Vec::new(),
        fx_chain: None,
        input_fx_chain: None,
    });
    id
}

fn item_for(path: &Path) -> ItemNode {
    let item_id = EntityId::new();
    let take_id = EntityId::new();
    ItemNode {
        id: item_id.clone(),
        item: Item {
            guid: item_id.as_str().to_string(),
            ..Default::default()
        },
        takes: vec![TakeNode {
            id: take_id.clone(),
            take: Take {
                guid: take_id.as_str().to_string(),
                is_active: true,
                ..Default::default()
            },
            source: SourceRef::File {
                path: path.to_string_lossy().into_owned(),
                kind: "WAVE".into(),
            },
            stretch_markers: Vec::new(),
            envelopes: Vec::new(),
        }],
        envelopes: Vec::new(),
    }
}
