//! Cue mode: the click, the count and the spoken guide, played here —
//! sample-locked to the engine this window drives.
//!
//! A window in Remote plays nothing; the system it drives (REAPER, a
//! Session engine) plays the song. In Cue it plays one thing more, the
//! monitor mix a player needs and nobody should send over a network: the
//! song's own click, count and guide, generated by its guide.
//!
//! The Cue engine is this process's own engine, the one Engine mode plays
//! a whole song on — Cue is the first stage of it (only the guide tracks
//! sound; Engine is every track):
//!
//! - **The song** opens the one way a song opens
//!   ([`crate::open::open_song_into`]) — its prepared `.session`, so the
//!   click and guide are exactly the song's, edits and all — and every
//!   track but the guide's is muted *here* (the shared session is not
//!   touched; this engine is nobody else's).
//! - **Which song** is the one the remote has current
//!   ([`crate::open::current_song`]); the remote's project names the song's
//!   file, found here by its path, or by its name in this machine's setlist
//!   (`FTS_SESSION_SETLIST`) when the path is another machine's.
//! - **The transport** is the remote's, to the sample: a
//!   [`daw::rpc::TransportLeader`] on the remote's `TransportSync` (its
//!   clock pinged, its stamped positions streamed) drives a
//!   [`daw_transport_sync::Follower`] on this engine's sync backend —
//!   a scheduled locate to start or follow a jump, then a resampled rate
//!   nudge of a fraction of a percent.
//!
//! One task does all of it, watching the requested mode and the remote's
//! current song: a pick here, a tab changed in REAPER, and the mode picker
//! are all the same thing to it.

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::Duration;

use daw::standalone::sync::Standalone;
use daw_transport_sync::{Correction, Follower, TransportBackend};

use crate::open::{AudioMode, set_cue_ready};

/// How often the follower corrects (and the task looks at the mode and
/// the song).
const TICK: Duration = Duration::from_millis(20);

/// Start the Cue task (once per process). It idles unless Cue is the
/// requested mode.
pub fn start() {
    static STARTED: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);
    if STARTED.swap(true, std::sync::atomic::Ordering::SeqCst) {
        return;
    }
    let Some(runtime) = crate::open::runtime() else {
        tracing::warn!("cue: no engine runtime; Cue stays pending");
        return;
    };
    runtime.spawn(run());
}

/// A song as the Cue engine has it.
struct Song {
    /// Its project in this process's engine.
    local: String,
}

/// What is being followed now.
struct Following {
    /// The remote's project.
    remote: String,
    local: String,
    leader: daw::rpc::TransportLeader,
    backend: Arc<dyn TransportBackend + Send + Sync>,
    follower: Follower,
}

async fn run() {
    let mut songs: HashMap<String, Song> = HashMap::new();
    let mut following: Option<Following> = None;
    let mut tick = tokio::time::interval(TICK);
    tick.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Skip);
    loop {
        tick.tick().await;
        if crate::open::mode().requested != AudioMode::Cue {
            // Not Cue (any more): let go, and be silent.
            if let Some(was) = following.take() {
                was.backend.stop(was.backend.snapshot().map_or(0.0, |s| s.playhead_seconds));
                set_cue_ready(false);
                tracing::info!(cue.song = %was.remote, "cue: stopped");
            }
            continue;
        }
        let Some(remote) = crate::open::current_song() else { continue };
        if following.as_ref().is_none_or(|f| f.remote != remote) {
            set_cue_ready(false);
            following = follow(&remote, &mut songs).await;
            if following.is_some() {
                set_cue_ready(true);
            }
        }
        if let Some(f) = following.as_mut() {
            let correction = f.leader.tick(&mut f.follower, f.backend.as_ref());
            if let Some(c) = correction
                && !matches!(c, Correction::Hold)
            {
                tracing::debug!(
                    cue.correction = ?c,
                    cue.drift_us = f.follower.controller().last_drift().map(|d| d * 1e6),
                    cue.offset_us = f.leader.offset_micros(),
                    "cue: following"
                );
            }
        }
    }
}

/// Make `remote` the song the Cue engine plays: load it (once), mute all
/// but its guide, put the audio on it, and lock its transport to the
/// remote's. `None` when the song is not on this machine (logged).
async fn follow(remote: &str, songs: &mut HashMap<String, Song>) -> Option<Following> {
    let daw = crate::open::cue_engine();
    if !songs.contains_key(remote) {
        let path = match local_song_file(remote).await {
            Some(path) => path,
            None => {
                tracing::warn!(cue.song = remote, "cue: this song is not on this machine; no click or guide for it");
                return None;
            }
        };
        let engine = daw.clone();
        let opened = tokio::task::spawn_blocking(move || open_cue_song(&engine, &path)).await;
        match opened {
            Ok(Ok(local)) => {
                songs.insert(remote.to_owned(), Song { local });
            }
            Ok(Err(e)) => {
                tracing::warn!(cue.song = remote, error = %e, "cue: the song did not open");
                return None;
            }
            Err(e) => {
                tracing::warn!(cue.song = remote, error = %e, "cue: the open task failed");
                return None;
            }
        }
    }
    let local = songs.get(remote)?.local.clone();
    crate::open::switch_to(daw, &local, true);
    let backend: Arc<dyn TransportBackend + Send + Sync> = Arc::new(daw.sync_backend(&local)?);
    let remote_daw = daw::rpc::Daw::try_get()?;
    let project = remote_daw.project(remote).await.ok()?;
    let leader = project.transport_sync().leader(daw::standalone::transport_sync::now_micros);
    tracing::info!(cue.song = remote, cue.local = %local, "cue: following the remote");
    Some(Following { remote: remote.to_owned(), local, leader, backend, follower: Follower::default() })
}

/// Open a song into the Cue engine the one way songs open, then mute every
/// track that is not the guide's. Returns its project.
fn open_cue_song(daw: &Standalone, path: &Path) -> eyre::Result<String> {
    let prepare = crate::prepare::Prepare::for_song(path);
    let (opened, plan) = crate::open::open_song_into(daw, path, &prepare)?;
    let ctx = daw::service::ProjectContext::Project(opened.project_guid.clone());
    let mut kept = 0usize;
    for track in daw::service::Tracks::all(daw, ctx.clone()) {
        let keep = session::guide::is_cue_track(&track.name, track.is_folder);
        if keep {
            kept = kept.saturating_add(1);
        }
        if let Err(e) =
            daw::service::Tracks::set_muted(daw, ctx.clone(), daw::service::TrackRef::Guid(track.guid.clone()), !keep)
        {
            tracing::warn!(cue.track = %track.name, error = %e, "cue: a track could not be muted");
        }
    }
    if kept == 0 {
        tracing::warn!(cue.song = %opened.name, "cue: the song has no generated click or guide");
    }
    tracing::info!(cue.song = %opened.name, cue.opened = %plan.open.display(), cue.tracks = kept, "cue: song ready");
    Ok(opened.project_guid)
}

/// The song file on this machine for the remote's project: its own path
/// when that exists here, else the song of the same name in this machine's
/// setlist.
async fn local_song_file(remote: &str) -> Option<PathBuf> {
    let daw = daw::rpc::Daw::try_get()?;
    let info = daw.project(remote).await.ok()?.info().await.ok()?;
    let path = PathBuf::from(&info.path);
    if !info.path.is_empty() && path.exists() {
        return Some(path);
    }
    let name = path.file_stem().map_or_else(|| info.name.clone(), |s| s.to_string_lossy().into_owned());
    let setlist = std::env::var_os("FTS_SESSION_SETLIST")?;
    crate::setlist::read_setlist(Path::new(&setlist))
        .ok()?
        .into_iter()
        .find(|song| song.file_stem().is_some_and(|s| s.to_string_lossy().eq_ignore_ascii_case(&name)))
}
